#ifndef PESP_CHAINPARAMSSEEDS_H
#define PESP_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the PESPCOIN network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x97,0x50,0x95,0x21}, 9599}
};

static SeedSpec6 pnSeed6_test[] = {
};
#endif // PESP_CHAINPARAMSSEEDS_H
